/* tslint:disable */
/* eslint-disable */
/**
 * Community API Documentation
 * <h2>REST service for accessing community probation information</h2><p>This service provides endpoints for accessing data primary sourced from National Delius about people that are of interest to HM Probation Service.</p><p>There is cross-over with the <b>prison-api</b> though suspects on remand will not be surfaced by this API unless that have previously been on probation.</p><div>This service is secured by <b>OAuth2</b> with tokens supplied by HMPPS Auth. Most read-only endpoints require the <b>ROLE_COMMUNITY</b> to access, but check each endpoint where this differs.<p>This service can be accessed in a number environments. For each environment a different set of OAuth2 credentials from HMPPS Auth are required</p><ul><li>Development: <b>https://community-api.dev.probation.service.justice.gov.uk</b></li><li>Test: <b>https://community-api.test.probation.service.justice.gov.uk</b></li><li>Pre-production: <b>https://community-api.pre-prod.delius.probation.hmpps.dsd.io</b></li><li>Production: <b>https://community-api.probation.service.justice.gov.uk</b></li></ul><div>
 *
 * The version of the OpenAPI document: 2021-05-21.4548.b3fe43e
 * Contact: dps-hmpps@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ContactType } from './contact-type';
import { Human } from './human';
import { KeyValue } from './key-value';
import { LicenceCondition } from './licence-condition';
import { LocalTime } from './local-time';
import { Nsi } from './nsi';
import { Requirement } from './requirement';
import { StaffHuman } from './staff-human';

/**
 * 
 * @export
 * @interface Contact
 */
export interface Contact {
    /**
     * 
     * @type {boolean}
     * @memberof Contact
     */
    alertActive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Contact
     */
    attended?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Contact
     */
    complied?: boolean;
    /**
     * 
     * @type {LocalTime}
     * @memberof Contact
     */
    contactEndTime?: LocalTime;
    /**
     * 
     * @type {number}
     * @memberof Contact
     */
    contactId: number;
    /**
     * 
     * @type {KeyValue}
     * @memberof Contact
     */
    contactOutcomeType?: KeyValue;
    /**
     * 
     * @type {LocalTime}
     * @memberof Contact
     */
    contactStartTime?: LocalTime;
    /**
     * 
     * @type {ContactType}
     * @memberof Contact
     */
    contactType: ContactType;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    createdDateTime?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Contact
     */
    documentLinked?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Contact
     */
    eventId?: number;
    /**
     * 
     * @type {KeyValue}
     * @memberof Contact
     */
    explanation?: KeyValue;
    /**
     * 
     * @type {number}
     * @memberof Contact
     */
    hoursCredited?: number;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    lastUpdatedDateTime?: string;
    /**
     * 
     * @type {LicenceCondition}
     * @memberof Contact
     */
    licenceCondition?: LicenceCondition;
    /**
     * 
     * @type {number}
     * @memberof Contact
     */
    linkedContactId?: number;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    notes?: string;
    /**
     * 
     * @type {Nsi}
     * @memberof Contact
     */
    nsi?: Nsi;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    partitionArea?: string;
    /**
     * 
     * @type {KeyValue}
     * @memberof Contact
     */
    probationArea?: KeyValue;
    /**
     * 
     * @type {Human}
     * @memberof Contact
     */
    providerEmployee?: Human;
    /**
     * 
     * @type {KeyValue}
     * @memberof Contact
     */
    providerLocation?: KeyValue;
    /**
     * 
     * @type {KeyValue}
     * @memberof Contact
     */
    providerTeam?: KeyValue;
    /**
     * 
     * @type {Requirement}
     * @memberof Contact
     */
    requirement?: Requirement;
    /**
     * 
     * @type {boolean}
     * @memberof Contact
     */
    softDeleted?: boolean;
    /**
     * 
     * @type {StaffHuman}
     * @memberof Contact
     */
    staff?: StaffHuman;
    /**
     * 
     * @type {KeyValue}
     * @memberof Contact
     */
    team?: KeyValue;
    /**
     * 
     * @type {boolean}
     * @memberof Contact
     */
    uploadLinked?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Contact
     */
    visorContact?: boolean;
}


