/* tslint:disable */
/* eslint-disable */
/**
 * Community API Documentation
 * <h2>REST service for accessing community probation information</h2><p>This service provides endpoints for accessing data primary sourced from National Delius about people that are of interest to HM Probation Service.</p><p>There is cross-over with the <b>prison-api</b> though suspects on remand will not be surfaced by this API unless that have previously been on probation.</p><div>This service is secured by <b>OAuth2</b> with tokens supplied by HMPPS Auth. Most read-only endpoints require the <b>ROLE_COMMUNITY</b> to access, but check each endpoint where this differs.<p>This service can be accessed in a number environments. For each environment a different set of OAuth2 credentials from HMPPS Auth are required</p><ul><li>Development: <b>https://community-api.dev.probation.service.justice.gov.uk</b></li><li>Test: <b>https://community-api.test.probation.service.justice.gov.uk</b></li><li>Pre-production: <b>https://community-api.pre-prod.delius.probation.hmpps.dsd.io</b></li><li>Production: <b>https://community-api.probation.service.justice.gov.uk</b></li></ul><div>
 *
 * The version of the OpenAPI document: 2021-05-21.4548.b3fe43e
 * Contact: dps-hmpps@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ContactDetails } from './contact-details';
import { IDs } from './ids';
import { OffenderAlias } from './offender-alias';
import { OffenderManager } from './offender-manager';
import { OffenderProfile } from './offender-profile';

/**
 * 
 * @export
 * @interface OffenderDetail
 */
export interface OffenderDetail {
    /**
     * identifies if this person is on an active sentence of interest to probation
     * @type {boolean}
     * @memberof OffenderDetail
     */
    activeProbationManagedSentence?: boolean;
    /**
     * 
     * @type {ContactDetails}
     * @memberof OffenderDetail
     */
    contactDetails?: ContactDetails;
    /**
     * deprecated, use activeProbationManagedSentence
     * @type {string}
     * @memberof OffenderDetail
     */
    currentDisposal?: string;
    /**
     * When true this record can not be viewed by specific probation staff
     * @type {boolean}
     * @memberof OffenderDetail
     */
    currentExclusion?: boolean;
    /**
     * When true this record can only be viewed by specific probation staff
     * @type {boolean}
     * @memberof OffenderDetail
     */
    currentRestriction?: boolean;
    /**
     * current tier
     * @type {string}
     * @memberof OffenderDetail
     */
    currentTier?: string;
    /**
     * 
     * @type {string}
     * @memberof OffenderDetail
     */
    dateOfBirth?: string;
    /**
     * Message to show staff who have been excluded from viewing this record
     * @type {string}
     * @memberof OffenderDetail
     */
    exclusionMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof OffenderDetail
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof OffenderDetail
     */
    gender?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OffenderDetail
     */
    middleNames?: Array<string>;
    /**
     * 
     * @type {Array<OffenderAlias>}
     * @memberof OffenderDetail
     */
    offenderAliases?: Array<OffenderAlias>;
    /**
     * 
     * @type {number}
     * @memberof OffenderDetail
     */
    offenderId: number;
    /**
     * 
     * @type {Array<OffenderManager>}
     * @memberof OffenderDetail
     */
    offenderManagers?: Array<OffenderManager>;
    /**
     * 
     * @type {OffenderProfile}
     * @memberof OffenderDetail
     */
    offenderProfile?: OffenderProfile;
    /**
     * 
     * @type {IDs}
     * @memberof OffenderDetail
     */
    otherIds?: IDs;
    /**
     * 
     * @type {string}
     * @memberof OffenderDetail
     */
    partitionArea?: string;
    /**
     * 
     * @type {string}
     * @memberof OffenderDetail
     */
    previousSurname?: string;
    /**
     * Message to show staff who have not been included to view this record
     * @type {string}
     * @memberof OffenderDetail
     */
    restrictionMessage?: string;
    /**
     * When true this record has been deleted
     * @type {boolean}
     * @memberof OffenderDetail
     */
    softDeleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OffenderDetail
     */
    surname?: string;
    /**
     * 
     * @type {string}
     * @memberof OffenderDetail
     */
    title?: string;
}


