/* tslint:disable */
/* eslint-disable */
/**
 * Community API Documentation
 * <h2>REST service for accessing community probation information</h2><p>This service provides endpoints for accessing data primary sourced from National Delius about people that are of interest to HM Probation Service.</p><p>There is cross-over with the <b>prison-api</b> though suspects on remand will not be surfaced by this API unless that have previously been on probation.</p><div>This service is secured by <b>OAuth2</b> with tokens supplied by HMPPS Auth. Most read-only endpoints require the <b>ROLE_COMMUNITY</b> to access, but check each endpoint where this differs.<p>This service can be accessed in a number environments. For each environment a different set of OAuth2 credentials from HMPPS Auth are required</p><ul><li>Development: <b>https://community-api.dev.probation.service.justice.gov.uk</b></li><li>Test: <b>https://community-api.test.probation.service.justice.gov.uk</b></li><li>Pre-production: <b>https://community-api.pre-prod.delius.probation.hmpps.dsd.io</b></li><li>Production: <b>https://community-api.probation.service.justice.gov.uk</b></li></ul><div>
 *
 * The version of the OpenAPI document: 2021-05-21.4548.b3fe43e
 * Contact: dps-hmpps@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { KeyValue } from './key-value';
import { StaffHuman } from './staff-human';

/**
 * 
 * @export
 * @interface Registration
 */
export interface Registration {
    /**
     * true if active
     * @type {boolean}
     * @memberof Registration
     */
    active?: boolean;
    /**
     * Latest Additional notes about the de-registration
     * @type {string}
     * @memberof Registration
     */
    deregisteringNotes?: string;
    /**
     * 
     * @type {StaffHuman}
     * @memberof Registration
     */
    deregisteringOfficer?: StaffHuman;
    /**
     * 
     * @type {KeyValue}
     * @memberof Registration
     */
    deregisteringProbationArea?: KeyValue;
    /**
     * 
     * @type {KeyValue}
     * @memberof Registration
     */
    deregisteringTeam?: KeyValue;
    /**
     * Latest Date removed from register
     * @type {string}
     * @memberof Registration
     */
    endDate?: string;
    /**
     * Date probation should review if the offender should still be on still register
     * @type {string}
     * @memberof Registration
     */
    nextReviewDate?: string;
    /**
     * Additional notes
     * @type {string}
     * @memberof Registration
     */
    notes?: string;
    /**
     * Count of number times this was de-registered
     * @type {number}
     * @memberof Registration
     */
    numberOfPreviousDeregistrations?: number;
    /**
     * Unique id of this offender
     * @type {number}
     * @memberof Registration
     */
    offenderId?: number;
    /**
     * 
     * @type {KeyValue}
     * @memberof Registration
     */
    register?: KeyValue;
    /**
     * 
     * @type {KeyValue}
     * @memberof Registration
     */
    registerCategory?: KeyValue;
    /**
     * 
     * @type {KeyValue}
     * @memberof Registration
     */
    registerLevel?: KeyValue;
    /**
     * 
     * @type {StaffHuman}
     * @memberof Registration
     */
    registeringOfficer?: StaffHuman;
    /**
     * 
     * @type {KeyValue}
     * @memberof Registration
     */
    registeringProbationArea?: KeyValue;
    /**
     * 
     * @type {KeyValue}
     * @memberof Registration
     */
    registeringTeam?: KeyValue;
    /**
     * Unique id of this registration
     * @type {number}
     * @memberof Registration
     */
    registrationId?: number;
    /**
     * Number of months a review should take place
     * @type {number}
     * @memberof Registration
     */
    reviewPeriodMonths?: number;
    /**
     * Literal visual colour this register represents
     * @type {string}
     * @memberof Registration
     */
    riskColour?: string;
    /**
     * Date added to register
     * @type {string}
     * @memberof Registration
     */
    startDate?: string;
    /**
     * 
     * @type {KeyValue}
     * @memberof Registration
     */
    type?: KeyValue;
    /**
     * true if the register is serious enough to warn the probation officer of risk to themselves
     * @type {boolean}
     * @memberof Registration
     */
    warnUser?: boolean;
}


