/* tslint:disable */
/* eslint-disable */
/**
 * Community API Documentation
 * <h2>REST service for accessing community probation information</h2><p>This service provides endpoints for accessing data primary sourced from National Delius about people that are of interest to HM Probation Service.</p><p>There is cross-over with the <b>prison-api</b> though suspects on remand will not be surfaced by this API unless that have previously been on probation.</p><div>This service is secured by <b>OAuth2</b> with tokens supplied by HMPPS Auth. Most read-only endpoints require the <b>ROLE_COMMUNITY</b> to access, but check each endpoint where this differs.<p>This service can be accessed in a number environments. For each environment a different set of OAuth2 credentials from HMPPS Auth are required</p><ul><li>Development: <b>https://community-api.dev.probation.service.justice.gov.uk</b></li><li>Test: <b>https://community-api.test.probation.service.justice.gov.uk</b></li><li>Pre-production: <b>https://community-api.pre-prod.delius.probation.hmpps.dsd.io</b></li><li>Production: <b>https://community-api.probation.service.justice.gov.uk</b></li></ul><div>
 *
 * The version of the OpenAPI document: 2021-05-21.4548.b3fe43e
 * Contact: dps-hmpps@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/appointments-api';
export * from './api/assessments-api';
export * from './api/authentication-and-users-api';
export * from './api/contact-and-attendance-api';
export * from './api/contacts-api';
export * from './api/convictions-api';
export * from './api/core-offender-api';
export * from './api/court-appearances-api';
export * from './api/courts-api';
export * from './api/custody-api';
export * from './api/documents-api';
export * from './api/events-api';
export * from './api/offender-managers-api';
export * from './api/operation-handler-api';
export * from './api/personal-circumstances-api';
export * from './api/popular-core-apis-api';
export * from './api/reference-data-api';
export * from './api/referrals-api';
export * from './api/risks-and-registrations-api';
export * from './api/sentence-dates-api';
export * from './api/sentence-requirements-and-breach-api';
export * from './api/staff-api';
export * from './api/teams-api';
export * from './api/users-api';

