version: '3.1'

services:
  hmpps-auth:
    depends_on:
      - community-api
    environment:
      - SPRING_PROFILES_ACTIVE=dev,delius,auth-seed
      - DELIUS_ENDPOINT_URL=http://community-api:8080

  oracle:
    container_name: oracle
    image: 895523100917.dkr.ecr.eu-west-2.amazonaws.com/hmpps/delius-test-db:latest
    networks:
      - hmpps
    ports:
      - "1521:1521"

  delius-api:
    image: public.ecr.aws/hmpps/delius-api:latest
    depends_on:
      - oracle
    restart: unless-stopped # need this to wait for oracle...
    container_name: delius-api
    networks:
      - hmpps
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ping" ]
    environment:
      SPRING_PROFILES_ACTIVE: dev,oracle
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@//oracle:1521/XEPDB1
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://hmpps-auth:9090/auth/.well-known/jwks.json
      FEATURES_TOKENVERIFICATION: "false"
      FEATURES_NSI_STATUS_HISTORY: "true"

  community-api:
    image: quay.io/hmpps/community-api:latest
    networks:
      - hmpps
    container_name: community-api
    depends_on:
      - delius-api
      - oracle
    restart: unless-stopped # need this to wait for oracle...
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ping" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//oracle:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=delius_app_schema
      - SPRING_DATASOURCE_PASSWORD=NDelius1
      - SPRING_FLYWAY_ENABLED=false
      - DELIUS_API_BASEURL=http://delius-api:8080

  app:
    depends_on:
      - community-api
    environment:
      COMMUNITY_API_URL: http://community-api:8080