version: '3.1'

services:
  redis:
    image: 'bitnami/redis:5.0'
    networks:
      - hmpps
    container_name: redis 
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth 
    ports:
      - "9090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev,auth-seed

  fake-api:
    build: ./fake-api
    networks:
      - hmpps
    container_name: fake-api
    ports:
      - "8082:8082"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ping" ]

  app:
    build: .
    networks:
      - hmpps
    container_name: hmpps-manage-supervisions
    depends_on:
      - redis
      - fake-api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: dev
      REDIS_HOST: redis
      HMPPS_AUTH_EXTERNAL_URL: http://localhost:9090/auth
      HMPPS_AUTH_URL: http://hmpps-auth:8080/auth
      COMMUNITY_API_URL: http://fake-api:8082
      # These will need to match new creds in the seed auth service auth
      API_CLIENT_ID: interventions
      API_CLIENT_SECRET: clientsecret
      SYSTEM_CLIENT_ID: interventions
      SYSTEM_CLIENT_SECRET: clientsecret

networks:
  hmpps:
