version: '3.1'

services:
  redis:
    image: 'bitnami/redis:5.0'
    networks:
      - hmpps
    container_name: redis 
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth
    networks:
      - hmpps
    container_name: hmpps-auth
    depends_on:
      - wiremock
    ports:
      - "9090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev,auth-seed,delius
      - DELIUS_ENDPOINT_URL=http://wiremock:8080/community-api
      - DELIUS_ROLES_MAPPINGS_MASBT001=ROLE_MANAGE_SUPERVISIONS_RO
      - DELIUS_ROLES_MAPPINGS_MASBT002=ROLE_MANAGE_SUPERVISIONS_RO,ROLE_MANAGE_SUPERVISIONS

  wiremock:
    image: rodolpheche/wiremock
    networks:
      - hmpps
    container_name: wiremock
    ports:
      - "9091:8080"
    volumes:
      - ./wiremock:/home/wiremock/mappings
    command:
      - -global-response-templating
      - -verbose

  app:
    build:
      context: .
      args:
        BUILD_NUMBER: local_compose
        GIT_REF: unknown
    networks:
      - hmpps
    container_name: hmpps-manage-supervisions
    depends_on:
      - redis
      - wiremock
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DEPLOYMENT_ENV=local
      - SESSION_SECRET=test
      - INGRESS_URL=http://localhost:3000
      - TOKEN_VERIFICATION_ENABLED=false
      - HMPPS_AUTH_EXTERNAL_URL=http://localhost:9090/auth
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      - COMMUNITY_API_URL=http://wiremock:8080/community-api
      - ASSESS_RISKS_AND_NEEDS_API_URL=http://wiremock:8080/assess-risks-and-needs
      - DELIUS_BASE_URL=http://localhost:9091/delius
      - OASYS_BASE_URL=http://localhost:9091/oasys
      - REDIS_HOST=redis
      - API_CLIENT_ID=interventions
      - API_CLIENT_SECRET=clientsecret
      - SYSTEM_CLIENT_ID=interventions
      - SYSTEM_CLIENT_SECRET=clientsecret

networks:
  hmpps:
