version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.11
  cypress: cypress-io/cypress@1
  slack: circleci/slack@4.1

executors:
  integration-test:
    docker:
      - image: cypress/base:14.17.3
        environment:
          TZ: "Europe/London"
      - image: circleci/redis:buster
      - image: rodolpheche/wiremock
        command: ['/docker-entrypoint.sh', '--port', '9091', '--global-response-templating']

  smoke-test:
    docker:
      - image: cypress/base:14.17.3


commands:
  install-build-deps:
    parameters:
      sudo:
        description: use sudo
        type: boolean
        default: true
    steps:
      - run:
          name: Install java
          command: |
            <<# parameters.sudo >>sudo <</ parameters.sudo >>mkdir -p /usr/share/man/man1 /usr/share/man/man2
            <<# parameters.sudo >>sudo <</ parameters.sudo >>apt-get update
            <<# parameters.sudo >>sudo <</ parameters.sudo >>apt-get install --no-install-recommends -y openjdk-11-jre-headless
      - run:
          name: Update npm
          command: <<# parameters.sudo >>sudo <</ parameters.sudo >>npm install -g npm

jobs:
  build-test:
    executor:
      name: hmpps/node
      tag: 14.17-browsers
    environment:
      TZ: "Europe/London"
    steps:
      - checkout
      - install-build-deps
      - restore_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: CYPRESS_INSTALL_BINARY=0 npm ci --no-audit
      - save_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          # this is a workaround for create_app_version adding a file to the workspace, which conflicts when it's used in multiple parallel steps
          name: Create app version string
          command: |
            DATE=$(date '+%Y-%m-%d')
            SHORT_SHA1=$(echo $CIRCLE_SHA1 | cut -c1-7)
            APP_VERSION=${DATE}.${CIRCLE_BUILD_NUM}.${SHORT_SHA1}
            echo "Created version string: ${APP_VERSION}"
            echo "export APP_VERSION=$APP_VERSION" >> $BASH_ENV
      - run:
          name: Build
          command: BUILD_NUMBER=$APP_VERSION GIT_REF=$CIRCLE_SHA1 GIT_BRANCH=$CIRCLE_BRANCH npm run build
      - run:
          name: Unit tests
          command: npm run test -- --maxWorkers=2 --ci
      - run:
          name: Lint
          command: npm run lint
      - store_test_results:
          path: test_results

  check_outdated:
    executor:
      name: hmpps/node
      tag: 14.17-browsers
    environment:
      TZ: "Europe/London"
    steps:
      - checkout
      - install-build-deps
      - restore_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: 'npm ci --no-audit'
      - run:
          name: Run check
          command: 'npm outdated @nestjs/core govuk-frontend'

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-test:
          context: hmpps-manage-supervisions
          filters:
            tags:
              ignore: /.*/
      - cypress/run:
          name: integration_test
          executor: integration-test
          post-checkout:
            - install-build-deps:
                sudo: false
          build: npm run build
          start: npm run start:e2e
          wait-on: 'http://localhost:3007/health/ping'
          no-workspace: true
          store_artifacts: true
          post-steps:
            - store_test_results:
                path: test_results
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          # this is named to match up with the deployment-tools job
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/build_docker:
          name: build_docker_nopublish
          publish: false
          filters:
            branches:
              ignore:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          context: hmpps-common-vars
          slack_notification: true
          slack_channel_name: "manage-a-supervision-notifications-dev"
          filters:
            branches:
              only:
                - main
          requires:
            - helm_lint
            - build-test
            - integration_test
            - build_docker
      - approve_postdev:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          show_changelog: true
          slack_notification: true
          slack_channel_name: "manage-a-supervision-notifications-preprod"
          requires:
            - approve_postdev
          context:
            - hmpps-common-vars
            - hmpps-manage-supervisions-preprod
      - approve_production:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          show_changelog: true
          slack_notification: true
          slack_channel_name: "manage-a-supervision-notifications"
          requires:
            - approve_production
          context:
            - hmpps-common-vars
            - hmpps-manage-supervisions-prod

  smoke_test:
    triggers:
      - schedule:
          cron: "0 9-17 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - cypress/run:
          name: smoke_test_dev
          executor: smoke-test
          config-file: cypress.dev.json
          spec: cypress/integration/smoke/**/*.spec.ts
          post-checkout:
            - install-build-deps:
                sudo: false
          no-workspace: true
          store_artifacts: true
          post-steps:
            - store_test_results:
                path: test_results
            - slack/notify:
                channel: manage-a-supervision-notifications-dev
                event: fail
                template: basic_fail_1
          context:
            - hmpps-common-vars
            - hmpps-manage-supervisions-smoke-test-dev

  security:
    triggers:
      - schedule:
          cron: "7 6 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - check_outdated
      - hmpps/npm_security_audit:
          slack_channel: manage-a-supervision-notifications
          context:
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          slack_channel: manage-a-supervision-notifications
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          slack_channel: manage-a-supervision-notifications
          context:
            - veracode-credentials
            - hmpps-common-vars

  security-weekly:
    triggers:
      - schedule:
          cron: "50 5 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/veracode_policy_scan:
          slack_channel: manage-a-supervision-notifications
          context:
            - veracode-credentials
            - hmpps-common-vars
