version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.2
  cypress: cypress-io/cypress@1

executors:
  integration-test:
    docker:
      - image: cypress/base:14.16.0
        environment:
          TZ: "Europe/London"
      - image: circleci/redis:buster
      - image: rodolpheche/wiremock
        command: ['/docker-entrypoint.sh', '--port', '9091']

jobs:
  build:
    executor:
      name: hmpps/node
      tag: 14.17-browsers
    environment:
      TZ: "Europe/London"
    steps:
      - checkout
      - run:
          name: Update npm
          command: sudo npm install -g npm
      - restore_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: CYPRESS_INSTALL_BINARY=0  npm ci --no-audit
      - save_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Record build info
          command: |
            npm run build
            DATE=$(date '+%Y-%m-%d')
            export BUILD_NUMBER=${DATE}.${CIRCLE_BUILD_NUM}
            export GIT_REF="$CIRCLE_SHA1"
            npm run record-build-info
      - run:
          name: Lint
          command: npm run lint
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - dist

  unit_test:
    executor:
      name: hmpps/node
      tag: 14.17-browsers
    environment:
      TZ: "Europe/London"
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - checkout
      - run:
          name: Update npm
          command: sudo npm install -g npm
      - attach_workspace:
          at: ~/app
      - run:
          name: unit tests
          command: npm run test -- --maxWorkers=2 --ci
      - store_test_results:
          path: test_results

  check_outdated:
    executor:
      name: hmpps/node
      tag: 14.17-browsers
    environment:
      TZ: "Europe/London"
    steps:
      - checkout
      - run:
          name: Update npm
          command: sudo npm install -g npm
      - restore_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: 'npm ci --no-audit'
      - run:
          name: Check version
          command: 'npm --version'
      - run:
          name: Run check
          command: 'npm outdated typescript govuk-frontend'

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
        filters:
          tags:
            ignore: /.*/
      - unit_test:
          requires:
            - build
      - cypress/run:
          name: integration_test
          executor: integration-test
          build: npm run build
          start: npm run start:e2e
          wait-on: 'http://localhost:3007/health/ping'
          no-workspace: true
          store_artifacts: true
          post-steps:
            - store_test_results:
                path: test_results
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - helm_lint
            - unit_test
            - integration_test
            - build_docker

  security:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - check_outdated
      - hmpps/npm_security_audit:
          context:
            - hmpps-common-vars
      - hmpps/veracode_policy_scan:
          context:
            - veracode-credentials
            - hmpps-common-vars
