version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.8
  cypress: cypress-io/cypress@1

executors:
  integration-test:
    docker:
      - image: cypress/base:14.16.0
        environment:
          TZ: "Europe/London"
      - image: circleci/redis:buster
      - image: rodolpheche/wiremock
        command: ['/docker-entrypoint.sh', '--port', '9091', '--global-response-templating']

commands:
  install-build-deps:
    parameters:
      sudo:
        description: use sudo
        type: boolean
        default: true
    steps:
      - run:
          name: Install java
          command: |
            <<# parameters.sudo >>sudo <</ parameters.sudo >>mkdir -p /usr/share/man/man1 /usr/share/man/man2
            <<# parameters.sudo >>sudo <</ parameters.sudo >>apt-get update
            <<# parameters.sudo >>sudo <</ parameters.sudo >>apt-get install --no-install-recommends -y openjdk-11-jre-headless
      - run:
          name: Update npm
          command: <<# parameters.sudo >>sudo <</ parameters.sudo >>npm install -g npm

jobs:
  build-test:
    executor:
      name: hmpps/node
      tag: 14.17-browsers
    environment:
      TZ: "Europe/London"
    steps:
      - checkout
      - install-build-deps
      - restore_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: CYPRESS_INSTALL_BINARY=0  npm ci --no-audit
      - save_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Record build info
          command: |
            npm run build
            DATE=$(date '+%Y-%m-%d')
            export BUILD_NUMBER=${DATE}.${CIRCLE_BUILD_NUM}
            export GIT_REF="$CIRCLE_SHA1"
            npm run record-build-info
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: unit tests
          command: npm run test -- --maxWorkers=2 --ci
      - store_test_results:
          path: test_results

  check_outdated:
    executor:
      name: hmpps/node
      tag: 14.17-browsers
    environment:
      TZ: "Europe/London"
    steps:
      - checkout
      - install-build-deps
      - restore_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: 'npm ci --no-audit'
      - run:
          name: Check version
          command: 'npm --version'
      - run:
          name: Run check
          command: 'npm outdated typescript govuk-frontend'

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-test:
          filters:
            tags:
              ignore: /.*/
      - cypress/run:
          name: integration_test
          executor: integration-test
          post-checkout:
            - install-build-deps:
                sudo: false
          build: npm run build
          start: npm run start:e2e
          wait-on: 'http://localhost:3007/health/ping'
          no-workspace: true
          store_artifacts: true
          post-steps:
            - store_test_results:
                path: test_results
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - helm_lint
            - build-test
            - integration_test
            - build_docker

  security:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - check_outdated
      - hmpps/npm_security_audit:
          context:
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          context:
            - hmpps-common-vars
      - hmpps/veracode_policy_scan:
          context:
            - veracode-credentials
            - hmpps-common-vars
