/* tslint:disable */
/* eslint-disable */
/**
 * Community API Documentation
 * <h2>REST service for accessing community probation information</h2><p>This service provides endpoints for accessing data primary sourced from National Delius about people that are of interest to HM Probation Service.</p><p>There is cross-over with the <b>prison-api</b> though suspects on remand will not be surfaced by this API unless that have previously been on probation.</p><div>This service is secured by <b>OAuth2</b> with tokens supplied by HMPPS Auth. Most read-only endpoints require the <b>ROLE_COMMUNITY</b> to access, but check each endpoint where this differs.<p>This service can be accessed in a number environments. For each environment a different set of OAuth2 credentials from HMPPS Auth are required</p><ul><li>Development: <b>https://community-api.dev.probation.service.justice.gov.uk</b></li><li>Test: <b>https://community-api.test.probation.service.justice.gov.uk</b></li><li>Pre-production: <b>https://community-api.pre-prod.delius.probation.hmpps.dsd.io</b></li><li>Production: <b>https://community-api.probation.service.justice.gov.uk</b></li></ul><div>
 *
 * The version of the OpenAPI document: 2021-05-21.4548.b3fe43e
 * Contact: dps-hmpps@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ErrorResponse } from '../model';
// @ts-ignore
import { OffenderAssessments } from '../model';
/**
 * AssessmentsApi - axios parameter creator
 * @export
 */
export const AssessmentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Return the assessments for a CRN
         * @param {string} crn CRN for the offender
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAssessmentsByCrnUsingGET: async (crn: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'crn' is not null or undefined
            assertParamExists('getAssessmentsByCrnUsingGET', 'crn', crn)
            const localVarPath = `/secure/offenders/crn/{crn}/assessments`
                .replace(`{${"crn"}}`, encodeURIComponent(String(crn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update offender tier. Requires ROLE_MANAGEMENT_TIER_UPDATE
         * @param {string} crn CRN for the offender
         * @param {'A0' | 'A1' | 'A2' | 'A3' | 'B0' | 'B1' | 'B2' | 'B3' | 'C0' | 'C1' | 'C2' | 'C3' | 'D0' | 'D1' | 'D2' | 'D3'} tier New tier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTierUsingPOST: async (crn: string, tier: 'A0' | 'A1' | 'A2' | 'A3' | 'B0' | 'B1' | 'B2' | 'B3' | 'C0' | 'C1' | 'C2' | 'C3' | 'D0' | 'D1' | 'D2' | 'D3', options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'crn' is not null or undefined
            assertParamExists('updateTierUsingPOST', 'crn', crn)
            // verify required parameter 'tier' is not null or undefined
            assertParamExists('updateTierUsingPOST', 'tier', tier)
            const localVarPath = `/secure/offenders/crn/{crn}/tier/{tier}`
                .replace(`{${"crn"}}`, encodeURIComponent(String(crn)))
                .replace(`{${"tier"}}`, encodeURIComponent(String(tier)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AssessmentsApi - functional programming interface
 * @export
 */
export const AssessmentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AssessmentsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Return the assessments for a CRN
         * @param {string} crn CRN for the offender
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAssessmentsByCrnUsingGET(crn: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OffenderAssessments>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAssessmentsByCrnUsingGET(crn, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update offender tier. Requires ROLE_MANAGEMENT_TIER_UPDATE
         * @param {string} crn CRN for the offender
         * @param {'A0' | 'A1' | 'A2' | 'A3' | 'B0' | 'B1' | 'B2' | 'B3' | 'C0' | 'C1' | 'C2' | 'C3' | 'D0' | 'D1' | 'D2' | 'D3'} tier New tier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateTierUsingPOST(crn: string, tier: 'A0' | 'A1' | 'A2' | 'A3' | 'B0' | 'B1' | 'B2' | 'B3' | 'C0' | 'C1' | 'C2' | 'C3' | 'D0' | 'D1' | 'D2' | 'D3', options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateTierUsingPOST(crn, tier, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AssessmentsApi - factory interface
 * @export
 */
export const AssessmentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AssessmentsApiFp(configuration)
    return {
        /**
         * 
         * @summary Return the assessments for a CRN
         * @param {string} crn CRN for the offender
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAssessmentsByCrnUsingGET(crn: string, options?: any): AxiosPromise<OffenderAssessments> {
            return localVarFp.getAssessmentsByCrnUsingGET(crn, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update offender tier. Requires ROLE_MANAGEMENT_TIER_UPDATE
         * @param {string} crn CRN for the offender
         * @param {'A0' | 'A1' | 'A2' | 'A3' | 'B0' | 'B1' | 'B2' | 'B3' | 'C0' | 'C1' | 'C2' | 'C3' | 'D0' | 'D1' | 'D2' | 'D3'} tier New tier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTierUsingPOST(crn: string, tier: 'A0' | 'A1' | 'A2' | 'A3' | 'B0' | 'B1' | 'B2' | 'B3' | 'C0' | 'C1' | 'C2' | 'C3' | 'D0' | 'D1' | 'D2' | 'D3', options?: any): AxiosPromise<void> {
            return localVarFp.updateTierUsingPOST(crn, tier, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getAssessmentsByCrnUsingGET operation in AssessmentsApi.
 * @export
 * @interface AssessmentsApiGetAssessmentsByCrnUsingGETRequest
 */
export interface AssessmentsApiGetAssessmentsByCrnUsingGETRequest {
    /**
     * CRN for the offender
     * @type {string}
     * @memberof AssessmentsApiGetAssessmentsByCrnUsingGET
     */
    readonly crn: string
}

/**
 * Request parameters for updateTierUsingPOST operation in AssessmentsApi.
 * @export
 * @interface AssessmentsApiUpdateTierUsingPOSTRequest
 */
export interface AssessmentsApiUpdateTierUsingPOSTRequest {
    /**
     * CRN for the offender
     * @type {string}
     * @memberof AssessmentsApiUpdateTierUsingPOST
     */
    readonly crn: string

    /**
     * New tier
     * @type {'A0' | 'A1' | 'A2' | 'A3' | 'B0' | 'B1' | 'B2' | 'B3' | 'C0' | 'C1' | 'C2' | 'C3' | 'D0' | 'D1' | 'D2' | 'D3'}
     * @memberof AssessmentsApiUpdateTierUsingPOST
     */
    readonly tier: 'A0' | 'A1' | 'A2' | 'A3' | 'B0' | 'B1' | 'B2' | 'B3' | 'C0' | 'C1' | 'C2' | 'C3' | 'D0' | 'D1' | 'D2' | 'D3'
}

/**
 * AssessmentsApi - object-oriented interface
 * @export
 * @class AssessmentsApi
 * @extends {BaseAPI}
 */
export class AssessmentsApi extends BaseAPI {
    /**
     * 
     * @summary Return the assessments for a CRN
     * @param {AssessmentsApiGetAssessmentsByCrnUsingGETRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssessmentsApi
     */
    public getAssessmentsByCrnUsingGET(requestParameters: AssessmentsApiGetAssessmentsByCrnUsingGETRequest, options?: any) {
        return AssessmentsApiFp(this.configuration).getAssessmentsByCrnUsingGET(requestParameters.crn, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update offender tier. Requires ROLE_MANAGEMENT_TIER_UPDATE
     * @param {AssessmentsApiUpdateTierUsingPOSTRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssessmentsApi
     */
    public updateTierUsingPOST(requestParameters: AssessmentsApiUpdateTierUsingPOSTRequest, options?: any) {
        return AssessmentsApiFp(this.configuration).updateTierUsingPOST(requestParameters.crn, requestParameters.tier, options).then((request) => request(this.axios, this.basePath));
    }
}
