/* tslint:disable */
/* eslint-disable */
/**
 * Community API Documentation
 * <h2>REST service for accessing community probation information</h2><p>This service provides endpoints for accessing data primary sourced from National Delius about people that are of interest to HM Probation Service.</p><p>There is cross-over with the <b>prison-api</b> though suspects on remand will not be surfaced by this API unless that have previously been on probation.</p><div>This service is secured by <b>OAuth2</b> with tokens supplied by HMPPS Auth. Most read-only endpoints require the <b>ROLE_COMMUNITY</b> to access, but check each endpoint where this differs.<p>This service can be accessed in a number environments. For each environment a different set of OAuth2 credentials from HMPPS Auth are required</p><ul><li>Development: <b>https://community-api.dev.probation.service.justice.gov.uk</b></li><li>Test: <b>https://community-api.test.probation.service.justice.gov.uk</b></li><li>Pre-production: <b>https://community-api.pre-prod.delius.probation.hmpps.dsd.io</b></li><li>Production: <b>https://community-api.probation.service.justice.gov.uk</b></li></ul><div>
 *
 * The version of the OpenAPI document: 2021-05-21.4548.b3fe43e
 * Contact: dps-hmpps@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ContextlessNotificationCreateRequest } from '../model';
// @ts-ignore
import { ErrorResponse } from '../model';
/**
 * ContactsApi - axios parameter creator
 * @export
 */
export const ContactsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Creates a Contact Log for a specified context
         * @param {string} contextName Name identifying preprocessing applied to the request
         * @param {string} crn crn
         * @param {number} sentenceId sentenceId
         * @param {ContextlessNotificationCreateRequest} contextlessNotificationCreateRequest contextlessNotificationCreateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notifyWithContextNameUsingPOST: async (contextName: string, crn: string, sentenceId: number, contextlessNotificationCreateRequest: ContextlessNotificationCreateRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'contextName' is not null or undefined
            assertParamExists('notifyWithContextNameUsingPOST', 'contextName', contextName)
            // verify required parameter 'crn' is not null or undefined
            assertParamExists('notifyWithContextNameUsingPOST', 'crn', crn)
            // verify required parameter 'sentenceId' is not null or undefined
            assertParamExists('notifyWithContextNameUsingPOST', 'sentenceId', sentenceId)
            // verify required parameter 'contextlessNotificationCreateRequest' is not null or undefined
            assertParamExists('notifyWithContextNameUsingPOST', 'contextlessNotificationCreateRequest', contextlessNotificationCreateRequest)
            const localVarPath = `/secure/offenders/crn/{crn}/sentences/{sentenceId}/notifications/context/{contextName}`
                .replace(`{${"contextName"}}`, encodeURIComponent(String(contextName)))
                .replace(`{${"crn"}}`, encodeURIComponent(String(crn)))
                .replace(`{${"sentenceId"}}`, encodeURIComponent(String(sentenceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(contextlessNotificationCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ContactsApi - functional programming interface
 * @export
 */
export const ContactsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ContactsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Creates a Contact Log for a specified context
         * @param {string} contextName Name identifying preprocessing applied to the request
         * @param {string} crn crn
         * @param {number} sentenceId sentenceId
         * @param {ContextlessNotificationCreateRequest} contextlessNotificationCreateRequest contextlessNotificationCreateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notifyWithContextNameUsingPOST(contextName: string, crn: string, sentenceId: number, contextlessNotificationCreateRequest: ContextlessNotificationCreateRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.notifyWithContextNameUsingPOST(contextName, crn, sentenceId, contextlessNotificationCreateRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ContactsApi - factory interface
 * @export
 */
export const ContactsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ContactsApiFp(configuration)
    return {
        /**
         * 
         * @summary Creates a Contact Log for a specified context
         * @param {string} contextName Name identifying preprocessing applied to the request
         * @param {string} crn crn
         * @param {number} sentenceId sentenceId
         * @param {ContextlessNotificationCreateRequest} contextlessNotificationCreateRequest contextlessNotificationCreateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notifyWithContextNameUsingPOST(contextName: string, crn: string, sentenceId: number, contextlessNotificationCreateRequest: ContextlessNotificationCreateRequest, options?: any): AxiosPromise<string> {
            return localVarFp.notifyWithContextNameUsingPOST(contextName, crn, sentenceId, contextlessNotificationCreateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for notifyWithContextNameUsingPOST operation in ContactsApi.
 * @export
 * @interface ContactsApiNotifyWithContextNameUsingPOSTRequest
 */
export interface ContactsApiNotifyWithContextNameUsingPOSTRequest {
    /**
     * Name identifying preprocessing applied to the request
     * @type {string}
     * @memberof ContactsApiNotifyWithContextNameUsingPOST
     */
    readonly contextName: string

    /**
     * crn
     * @type {string}
     * @memberof ContactsApiNotifyWithContextNameUsingPOST
     */
    readonly crn: string

    /**
     * sentenceId
     * @type {number}
     * @memberof ContactsApiNotifyWithContextNameUsingPOST
     */
    readonly sentenceId: number

    /**
     * contextlessNotificationCreateRequest
     * @type {ContextlessNotificationCreateRequest}
     * @memberof ContactsApiNotifyWithContextNameUsingPOST
     */
    readonly contextlessNotificationCreateRequest: ContextlessNotificationCreateRequest
}

/**
 * ContactsApi - object-oriented interface
 * @export
 * @class ContactsApi
 * @extends {BaseAPI}
 */
export class ContactsApi extends BaseAPI {
    /**
     * 
     * @summary Creates a Contact Log for a specified context
     * @param {ContactsApiNotifyWithContextNameUsingPOSTRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactsApi
     */
    public notifyWithContextNameUsingPOST(requestParameters: ContactsApiNotifyWithContextNameUsingPOSTRequest, options?: any) {
        return ContactsApiFp(this.configuration).notifyWithContextNameUsingPOST(requestParameters.contextName, requestParameters.crn, requestParameters.sentenceId, requestParameters.contextlessNotificationCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
