/* tslint:disable */
/* eslint-disable */
/**
 * Community API Documentation
 * <h2>REST service for accessing community probation information</h2><p>This service provides endpoints for accessing data primary sourced from National Delius about people that are of interest to HM Probation Service.</p><p>There is cross-over with the <b>prison-api</b> though suspects on remand will not be surfaced by this API unless that have previously been on probation.</p><div>This service is secured by <b>OAuth2</b> with tokens supplied by HMPPS Auth. Most read-only endpoints require the <b>ROLE_COMMUNITY</b> to access, but check each endpoint where this differs.<p>This service can be accessed in a number environments. For each environment a different set of OAuth2 credentials from HMPPS Auth are required</p><ul><li>Development: <b>https://community-api.dev.probation.service.justice.gov.uk</b></li><li>Test: <b>https://community-api.test.probation.service.justice.gov.uk</b></li><li>Pre-production: <b>https://community-api.pre-prod.delius.probation.hmpps.dsd.io</b></li><li>Production: <b>https://community-api.probation.service.justice.gov.uk</b></li></ul><div>
 *
 * The version of the OpenAPI document: 2021-05-21.4548.b3fe43e
 * Contact: dps-hmpps@digital.justice.gov.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CourtAppearanceBasicWrapper } from '../model';
// @ts-ignore
import { CourtAppearanceMinimalWrapper } from '../model';
// @ts-ignore
import { ErrorResponse } from '../model';
/**
 * CourtAppearancesApi - axios parameter creator
 * @export
 */
export const CourtAppearancesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Returns all court appearances on and after the given date.
         * @param {string} fromDate Return court appearances from the given date. Defaults to today if not provided.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCourtAppearancesUsingGET: async (fromDate: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'fromDate' is not null or undefined
            assertParamExists('getCourtAppearancesUsingGET', 'fromDate', fromDate)
            const localVarPath = `/secure/courtAppearances`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (fromDate !== undefined) {
                localVarQueryParameter['fromDate'] = fromDate;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Returns all court appearances associated with the CRN for the conviction ID.
         * @param {number} convictionId convictionId
         * @param {string} crn crn
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOffenderCourtAppearancesByCrnUsingGET: async (convictionId: number, crn: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'convictionId' is not null or undefined
            assertParamExists('getOffenderCourtAppearancesByCrnUsingGET', 'convictionId', convictionId)
            // verify required parameter 'crn' is not null or undefined
            assertParamExists('getOffenderCourtAppearancesByCrnUsingGET', 'crn', crn)
            const localVarPath = `/secure/offenders/crn/{crn}/convictions/{convictionId}/courtAppearances`
                .replace(`{${"convictionId"}}`, encodeURIComponent(String(convictionId)))
                .replace(`{${"crn"}}`, encodeURIComponent(String(crn)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CourtAppearancesApi - functional programming interface
 * @export
 */
export const CourtAppearancesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CourtAppearancesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Returns all court appearances on and after the given date.
         * @param {string} fromDate Return court appearances from the given date. Defaults to today if not provided.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCourtAppearancesUsingGET(fromDate: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CourtAppearanceMinimalWrapper>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCourtAppearancesUsingGET(fromDate, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Returns all court appearances associated with the CRN for the conviction ID.
         * @param {number} convictionId convictionId
         * @param {string} crn crn
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOffenderCourtAppearancesByCrnUsingGET(convictionId: number, crn: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CourtAppearanceBasicWrapper>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOffenderCourtAppearancesByCrnUsingGET(convictionId, crn, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CourtAppearancesApi - factory interface
 * @export
 */
export const CourtAppearancesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CourtAppearancesApiFp(configuration)
    return {
        /**
         * 
         * @summary Returns all court appearances on and after the given date.
         * @param {string} fromDate Return court appearances from the given date. Defaults to today if not provided.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCourtAppearancesUsingGET(fromDate: string, options?: any): AxiosPromise<CourtAppearanceMinimalWrapper> {
            return localVarFp.getCourtAppearancesUsingGET(fromDate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Returns all court appearances associated with the CRN for the conviction ID.
         * @param {number} convictionId convictionId
         * @param {string} crn crn
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOffenderCourtAppearancesByCrnUsingGET(convictionId: number, crn: string, options?: any): AxiosPromise<CourtAppearanceBasicWrapper> {
            return localVarFp.getOffenderCourtAppearancesByCrnUsingGET(convictionId, crn, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getCourtAppearancesUsingGET operation in CourtAppearancesApi.
 * @export
 * @interface CourtAppearancesApiGetCourtAppearancesUsingGETRequest
 */
export interface CourtAppearancesApiGetCourtAppearancesUsingGETRequest {
    /**
     * Return court appearances from the given date. Defaults to today if not provided.
     * @type {string}
     * @memberof CourtAppearancesApiGetCourtAppearancesUsingGET
     */
    readonly fromDate: string
}

/**
 * Request parameters for getOffenderCourtAppearancesByCrnUsingGET operation in CourtAppearancesApi.
 * @export
 * @interface CourtAppearancesApiGetOffenderCourtAppearancesByCrnUsingGETRequest
 */
export interface CourtAppearancesApiGetOffenderCourtAppearancesByCrnUsingGETRequest {
    /**
     * convictionId
     * @type {number}
     * @memberof CourtAppearancesApiGetOffenderCourtAppearancesByCrnUsingGET
     */
    readonly convictionId: number

    /**
     * crn
     * @type {string}
     * @memberof CourtAppearancesApiGetOffenderCourtAppearancesByCrnUsingGET
     */
    readonly crn: string
}

/**
 * CourtAppearancesApi - object-oriented interface
 * @export
 * @class CourtAppearancesApi
 * @extends {BaseAPI}
 */
export class CourtAppearancesApi extends BaseAPI {
    /**
     * 
     * @summary Returns all court appearances on and after the given date.
     * @param {CourtAppearancesApiGetCourtAppearancesUsingGETRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CourtAppearancesApi
     */
    public getCourtAppearancesUsingGET(requestParameters: CourtAppearancesApiGetCourtAppearancesUsingGETRequest, options?: any) {
        return CourtAppearancesApiFp(this.configuration).getCourtAppearancesUsingGET(requestParameters.fromDate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Returns all court appearances associated with the CRN for the conviction ID.
     * @param {CourtAppearancesApiGetOffenderCourtAppearancesByCrnUsingGETRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CourtAppearancesApi
     */
    public getOffenderCourtAppearancesByCrnUsingGET(requestParameters: CourtAppearancesApiGetOffenderCourtAppearancesByCrnUsingGETRequest, options?: any) {
        return CourtAppearancesApiFp(this.configuration).getOffenderCourtAppearancesByCrnUsingGET(requestParameters.convictionId, requestParameters.crn, options).then((request) => request(this.axios, this.basePath));
    }
}
