---
# Values here are the same across all environments
generic-service:
  nameOverride: hmpps-manage-supervisions

  image:
    repository: quay.io/hmpps/hmpps-manage-supervisions
    tag: latest
    pullPolicy: IfNotPresent
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    cert_secret: hmpps-manage-supervisions-cert
    path: /

  allowlist:
    mojvpn: "81.134.202.29/32"
    moj-official-tgw-prod: "51.149.250.0/24"
    moj-official-tgw-preprod: "51.149.251.0/24"

generic-prometheus-alerts:
  targetApplication: hmpps-manage-supervisions

