---
# Values here are the same across all environments
generic-service:
  nameOverride: hmpps-manage-supervisions

  image:
    repository: quay.io/hmpps/hmpps-manage-supervisions
    tag: latest
    pullPolicy: IfNotPresent
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    path: /

  livenessProbe:
    httpGet:
      path: /health/ping

  readinessProbe:
    httpGet:
      path: /health

  env:
    NODE_ENV: "production"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"

  namespace_secrets:
    hmpps-manage-supervisions:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
      SESSION_SECRET: "SESSION_SECRET"
      SENTRY_DSN: "SENTRY_DSN"

    hmpps-manage-supervisions-elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"

generic-prometheus-alerts:
  targetApplication: hmpps-manage-supervisions

