# This is a YAML-formatted file.
generic-service:

  allowlist:
    mojvpn: "81.134.202.29/32"
    moj-official-tgw-alpha: "35.176.93.186/32" # Gateway IP address for Global Protect alpha vpn firewall

