generic-service:

  replicaCount: 2

  ingress:
    host: manage-supervisions.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-manage-supervisions-cert

  env:
    DEPLOYMENT_ENV: prod
    HMPPS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    TOKEN_VERIFICATION_API_URL: https://token-verification-api.prison.service.justice.gov.uk
    TOKEN_VERIFICATION_ENABLED: true
    COMMUNITY_API_URL: https://community-api-secure.probation.service.justice.gov.uk
    ASSESS_RISKS_AND_NEEDS_API_URL: https://assess-risks-and-needs.hmpps.service.justice.gov.uk
    DELIUS_BASE_URL: https://ndelius.probation.service.justice.gov.uk
    OASYS_BASE_URL: https://bridge-oasys.az.justice.gov.uk
    INGRESS_URL: https://manage-supervisions.hmpps.service.justice.gov.uk
    RECORD_OUTCOME: false

  allowlist:
    mojvpn: "81.134.202.29/32"
    moj-official-tgw-alpha: "35.176.93.186/32" # Gateway IP address for Global Protect alpha vpn firewall
    shef-digital-studio: "217.33.148.210/32" # Digital studio
    ark-internet-1: "195.59.75.0/24"   # ARK internet (DOM1)
    ark-internet-2: "194.33.192.0/25"  # ARK internet (DOM1)
    ark-internet-3: "194.33.193.0/25"  # ARK internet (DOM1)
    ark-internet-4: "194.33.196.0/25"  # ARK internet (DOM1)
    ark-internet-5: "194.33.197.0/25"  # ARK internet (DOM1)
