import {
  AppointmentType,
  AppointmentTypeOrderTypes,
  AppointmentTypeRequiresLocation,
} from '../../src/server/community-api/client'
import { SeedFn } from './wiremock'

export const appointmentTypes: SeedFn = ({ client }) => {
  client.community.get('/secure/appointment-types').returns(APPOINTMENT_TYPES)
}

export const APPOINTMENT_TYPES: AppointmentType[] = [
  {
    contactType: 'CITI',
    description: 'Citizenship Induction Session (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'CITA',
    description: 'Citizenship Alcohol Session (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja],
  },
  {
    contactType: 'CITD',
    description: 'Citizenship Drugs Session (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'CITE',
    description: 'Citizenship Emotions Session (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'CITL',
    description: 'Citizenship Lifestyle Session (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'CITR',
    description: 'Citizenship Relationships Session (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'CITV',
    description: 'Citizenship Variation from Citizenship (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'CITN',
    description: 'Citizenship Next Steps Session/Handover (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'CIRS',
    description: 'Citizenship Induct. Sex Offender (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'APAT',
    description: 'Programme Session (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'APRE',
    description: 'Programme Pre-work (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'APOS',
    description: 'Programme Post Work (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'CHVS',
    description: 'Home Visit to Case (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.NotRequired,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'COAP',
    description: 'Planned Office Visit (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'CAIE',
    description: 'IOM External Provider Appointment',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'CAIS',
    description: 'IOM Office Visit planned',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'EAPK',
    description: 'AP - Keyworker Session (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'CGTS',
    description: 'Test',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'C007',
    description: 'ETE Appointment (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'C031',
    description: 'Other Appointment (Non NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'C085',
    description: 'Programme Session (Non NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'C086',
    description: 'Programme Pre-Work (Non NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'C087',
    description: 'Programme Post-Work (Non NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'C089',
    description: 'Alcohol Key Worker Session (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'C090',
    description: 'Drug Key Worker Session (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'C101',
    description: 'Appointment with External Agency',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'C133',
    description: 'Clinic Appointment (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'C175',
    description: 'ETE Appointment (Non NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'C234',
    description: 'Restorative Justice Attendance',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'C240',
    description: 'Drug Test (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'C241',
    description: 'Court Review (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'C242',
    description: 'Drug Group Work Session (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'C243',
    description: 'Alcohol Group Work Session (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'C251',
    description: 'Post Citizenship Contact (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'C258',
    description: 'CSS Appointment - Enforceable (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'C259',
    description: 'CSS Appointment with Volunteer / Agency',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'C264',
    description: 'OM Appointments During Comunity Phase',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'C307',
    description: 'IAG Appointment (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'C314',
    description: 'Appointment with External Agency (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'C334',
    description: 'Biometric Reporting Appointment',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'C352',
    description: 'Learning and Skills Appointment (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'C353',
    description: 'Finance / Benefits / Debt Appointment (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'C379',
    description: 'START Programme Attendance (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'C444',
    description: 'Other Appointment (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'APPA03',
    description: 'AP PA - Accommodation',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'ATCA',
    description: 'Attendance Centre Appointment (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'CGAP01',
    description: 'Pre group 1:1 - Motivating and engaging',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGAP02',
    description: 'Session 1 - Introduction',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGAP03',
    description: 'Session 2 - Why I did it',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGAP04',
    description: 'Session 3 - What I believe',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGAP05',
    description: 'Session 4 - Living up to expectations',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGAP06',
    description: 'Session 5 - Accurate Perceptions?',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGAP07',
    description: 'Session 6 - Coping with other people',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGAP08',
    description: 'Session 7 - Review',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGAP09',
    description: 'Session 8 - My Goals, My Plan',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGAP10',
    description: "Post-group 1:1-Applying what I've learned...",
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGEN01',
    description: 'Pre-Group 1-1',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGEN02',
    description: 'Session 1 - Introductions',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGEN03',
    description: 'Session 2.  Lifestyles',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGEN04',
    description: 'Session 3.  Life management plans',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGEN05',
    description: 'Session 4.  Progress review',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGEN06',
    description: 'Session 5.  Emotional Management (Attitudes)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGEN07',
    description: 'Session 6.  Coping with Reality 1',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGEN08',
    description: 'Session 7.  Coping with Reality 2',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGEN09',
    description: 'Session 8.  Offending and its Consequences',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGEN10',
    description: 'Session 9.  Alternative Lifestyles',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGEN11',
    description: 'Session 10. Action plans and the Future',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGIR01',
    description: 'Assessment One to One (Induction) ',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGIR02',
    description: 'Session 1: Introductions',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGIR03',
    description: 'Session 2: What is Domestic Abuse?',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGIR04',
    description: 'Session 3: What causes Domestic Abuse?',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGIR05',
    description: 'Session 4: Identifying core beliefs',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGIR06',
    description: 'Session 5: Identifying the impact on others',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGIR07',
    description: 'Session 6: Identifying the case for change',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGIR08',
    description: 'Session 7: Control of Emotions',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGIR09',
    description: 'Session 8: Promoting positive self talk',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGIR10',
    description: 'Session 9: Negotiation skills',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGIR11',
    description: 'Session 10: Structured Time Outs',
    requiresLocation: AppointmentTypeRequiresLocation.NotRequired,
    orderTypes: [],
  },
  {
    contactType: 'CGIR12',
    description: 'Session 11: Review',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'CGIR13',
    description: 'Session 12: Planning for the Future',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'COPT',
    description: 'Planned Telephone Contact (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'DLND2',
    description: 'Cannabis Groupwork Session (DLNR)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'DLND3',
    description: 'NPS Groupwork Session (DLNR)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'DLNRBRA',
    description: 'Biometric Reporting Appointment (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja, AppointmentTypeOrderTypes.Legacy],
  },
  {
    contactType: 'DLNRD1',
    description: 'Cocaine Groupwork Session (DLNR)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'DLNRD4',
    description: 'Cocaine 1:1 Session (DLNR)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'DLNRD5',
    description: 'Cannabis 1:1 session (DLNR)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'DLNRD6',
    description: 'NPS 1:1 Session (DLNR)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'KRAR01',
    description: 'Session 1 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'KRAR02',
    description: 'Session 2 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'KRAR03',
    description: 'Session 3 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'KRAR04',
    description: 'Session 4 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'KRAR05',
    description: 'Session 5 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'KRAR06',
    description: 'Session 6 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'KRAR07',
    description: 'Session 7 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'KRAR08',
    description: 'Session 8 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'KRAR09',
    description: 'Session 9 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'KRAR10',
    description: 'Session 10 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'KRAR11',
    description: 'Session 11 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'KRAR12',
    description: 'Session 12 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'KRAR13',
    description: 'Session 13 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'KRAR14',
    description: 'Session 14 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'MSRP01',
    description: 'MSRP Module',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'MSRP19',
    description: 'Module 19(NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'MSRP20',
    description: 'Module 20(NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'MSRP21',
    description: 'Learning Module 1(NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'MSRP22',
    description: 'Learning Module 2 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'MSRP23',
    description: 'Learning Module 3 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'MSRP24',
    description: 'Learning Module 4 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'MSRP25',
    description: 'Learning Module 5 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'MSRP26',
    description: 'Learning Module 6 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'MSRP27',
    description: 'Learning Module 7 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'MSRP28',
    description: 'Learning Module 8 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'MSRP29',
    description: 'Learning Module 9 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'MSRP30',
    description: 'Learning Module 10 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'MSRP31',
    description: 'Practice Module 1 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'MSRP32',
    description: 'Practice Module 2 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'MSRP33',
    description: 'Practice Module 3 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'MSRP34',
    description: 'Practice Module 4 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'MSRP35',
    description: 'Practice Module 5 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'MSRP36',
    description: 'Practice Module 6 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'MSRP37',
    description: 'Practice Module 7 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'MSRP41',
    description: 'Doing Module 1 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'MSRP42',
    description: 'Doing Module 2 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'MSRP43',
    description: 'Doing Module 3 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'MSRP44',
    description: 'Doing Module 4 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'MSRP45',
    description: 'Doing Module 5 (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Optional,
    orderTypes: [],
  },
  {
    contactType: 'NBRS1',
    description: 'Session 1 - Lets get confident & go to Work',
    requiresLocation: AppointmentTypeRequiresLocation.NotRequired,
    orderTypes: [],
  },
  {
    contactType: 'NBRS2',
    description: 'Session 2: Me - A Great Employee',
    requiresLocation: AppointmentTypeRequiresLocation.NotRequired,
    orderTypes: [],
  },
  {
    contactType: 'NBRS3',
    description: 'Session 3: Getting Motivated to Overcome Hurdles',
    requiresLocation: AppointmentTypeRequiresLocation.NotRequired,
    orderTypes: [],
  },
  {
    contactType: 'NBRS4',
    description: 'Session 4: Selling Myself on Paper ',
    requiresLocation: AppointmentTypeRequiresLocation.NotRequired,
    orderTypes: [],
  },
  {
    contactType: 'NBRS5',
    description: "Session 5: Let's Have a Go",
    requiresLocation: AppointmentTypeRequiresLocation.NotRequired,
    orderTypes: [],
  },
  {
    contactType: 'NBRS6',
    description: 'Session 6: Celebration event',
    requiresLocation: AppointmentTypeRequiresLocation.NotRequired,
    orderTypes: [],
  },
  {
    contactType: 'POLY01',
    description: 'Polygraph Attendance (NS)',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'RJC01',
    description: 'Restorative Justice Preparation Work',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'RJC02',
    description: 'Restorative Justice Conference ',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'RJC03',
    description: 'Restorative Justice Post Work',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [],
  },
  {
    contactType: 'RJI01',
    description: 'Restorative Justice Individual Tailored Work',
    requiresLocation: AppointmentTypeRequiresLocation.Required,
    orderTypes: [AppointmentTypeOrderTypes.Cja],
  },
]
